### ISSUE TITLE
I'd like to propose an alternate history :)

### ISSUE THREAD

**Issue by bobthecow** [lukeed/gulp-rev-manifest#1]
https://github.com/bobthecow/gulp-rev-manifest/commits/master

That's all your new commits cherry-picked on top of the original repo. This means we don't lose history or context or pull requests or issues or commit messages for any of the lines of code that moved to this repo :)

I figure it's early enough in the life of this repo that you could just force push this branch to your master, delete the `v1.0.0` tag, cut a new `v1.1.0` tag and publish it to npm.

**Comment by bobthecow** [comment]
for example, this blame: https://github.com/bobthecow/gulp-rev-manifest/blame/master/index.js

**Comment by lukeed** [comment]
Added you as collab! I agree with you, so go ahead & work your magic 👍 

Let me know if & when to publish/unpublish on npm.

**Comment by bobthecow** [comment]
Done: https://github.com/lukeed/gulp-rev-manifest/commits/master

**Comment by bobthecow** [comment]
You'll prolly want to `git fetch origin && git reset --hard origin/master` to nuke your local copy of those commits.

**Comment by lukeed** [comment]
Different computer 😉, fresh clone. Will publish as `1.1.0` now

**Comment by bobthecow** [comment]
The tag for v1.0.0 has been deleted on GitHub as well. I'm not sure if it'll cause any problems to have the other code on npm under the v1.0.0 release or not.

**Comment by bobthecow** [comment]
should prolly `npm deprecate` or `npm unpublish` that version as well. again, it's early enough in the life of this that an `unpublish` is likely okay.

**Comment by lukeed** [comment]
Unpublished `1.0.0` and then published `1.1.0`. Thanks for your help @bobthecow !

**Comment by bobthecow** [comment]
Great. Thank you!
